language: php

before_script:
  - ./tests/enable-php-extensions.sh
  - composer update --dev

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - memcached
  - redis-server

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 src/
  - phpunit --configuration phpunit.xml.travisci
