language: php

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar update --dev

php:
  - 5.3
  - 5.4
  - 5.5

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 src/
